# Generated by Django 5.2.5 on 2025-08-23 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeographicRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('serial_number', models.CharField(blank=True, help_text='Serial number of an instrument if it exists', max_length=255, null=True, unique=True, verbose_name='Serial Number')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'ordering': ['name', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Program name')),
                ('description', models.TextField(verbose_name='Program description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cruises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the cruise e.g 'CAR2025002'", max_length=20, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('descriptor', models.CharField(blank=True, help_text="MEDS assigned description of the cruise e.g '18QL25002'", max_length=20, null=True, verbose_name='Descriptor')),
                ('chief_scientists', models.ManyToManyField(related_name='chief_scientists', to=settings.AUTH_USER_MODEL, verbose_name='Chief Scientists')),
                ('data_managers', models.ManyToManyField(related_name='data_managers', to=settings.AUTH_USER_MODEL, verbose_name='Data Managers')),
                ('locations', models.ManyToManyField(blank=True, related_name='locations', to='core.geographicregions', verbose_name='Locations')),
                ('programs', models.ManyToManyField(related_name='programs', to='core.programs', verbose_name='programs')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_file_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='File location')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_data', to='core.cruises')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mission_data', to='core.datastatus', verbose_name='Process Status')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mission_data', to='core.datatypes')),
                ('instruments', models.ManyToManyField(blank=True, related_name='instruments', to='core.instruments', verbose_name='Instruments')),
            ],
        ),
        migrations.CreateModel(
            name='DataFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='File Name')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('submitted_date', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='core.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='GroupProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='MooredInstruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(help_text='Serial Number or name given to the moored instrument', max_length=20, unique=True, verbose_name='Name')),
                ('instruments', models.ManyToManyField(blank=True, related_name='moored_instruments', to='core.instruments', verbose_name='Instruments')),
            ],
        ),
    ]
