# Generated by Django 5.2.5 on 2026-03-13 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(db_column='country_seq', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=45, verbose_name='Name')),
                ('short_name', models.CharField(db_column='short_name', help_text='2-character country code', max_length=2, verbose_name='Short Name')),
                ('code', models.IntegerField(blank=True, help_text='2-digit country code', null=True, verbose_name='Code')),
            ],
            options={
                'db_table': 'lu_countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(db_column='dataset_seq', primary_key=True, serialize=False)),
                ('legacy_file_location', models.CharField(blank=True, db_column='legacy_file_location', max_length=255, null=True, verbose_name='File location')),
            ],
            options={
                'db_table': 'datasets',
                'ordering': ['mission', 'data_type'],
            },
        ),
        migrations.CreateModel(
            name='DatasetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=20, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'lu_dataset_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=25, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'lu_dataset_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(db_column='extension', max_length=25, verbose_name='Extension')),
                ('description', models.CharField(db_column='description', max_length=255, verbose_name='Description')),
            ],
            options={
                'db_table': 'lu_file_types',
                'ordering': ['extension'],
            },
        ),
        migrations.CreateModel(
            name='GeographicRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=50, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'lu_geographic_regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Legs',
            fields=[
                ('id', models.AutoField(db_column='leg_seq', primary_key=True, serialize=False)),
                ('number', models.IntegerField(db_column='number', verbose_name='Leg Number')),
                ('start_date', models.DateField(db_column='start_date', verbose_name='Start Date')),
                ('end_date', models.DateField(db_column='end_date', verbose_name='End Date')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'legs',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', help_text="The name of the cruise e.g 'CAR2025002'", max_length=20, verbose_name='Name')),
                ('descriptor', models.CharField(blank=True, db_column='meds_descriptor', help_text="MEDS assigned description of the cruise e.g '18QL25002'", max_length=20, null=True, verbose_name='Descriptor')),
                ('ppt_id', models.IntegerField(blank=True, db_column='ppt_id', help_text='Project Planning Tool ID to link to project details', null=True, verbose_name='PPT id')),
            ],
            options={
                'db_table': 'missions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_column='last_name', max_length=50, verbose_name='Last Name')),
                ('first_name', models.CharField(db_column='first_name', max_length=50, verbose_name='First Name')),
            ],
            options={
                'db_table': 'lu_participants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=30, verbose_name='Name')),
                ('description', models.CharField(db_column='description', max_length=255, verbose_name='Description')),
            ],
            options={
                'db_table': 'lu_positions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=45, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'lu_programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=45, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'lu_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataFiles',
            fields=[
                ('id', models.AutoField(db_column='file_seq', primary_key=True, serialize=False)),
                ('file_name', models.CharField(db_column='file_name', max_length=50, verbose_name='File Name')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, db_column='submitted_date')),
                ('is_archived', models.BooleanField(db_column='is_archived', default=False, verbose_name='Is archived')),
                ('submitted_by', models.ForeignKey(db_column='submitted_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('data', models.ForeignKey(db_column='dataset_seq', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.dataset')),
                ('file_type', models.ForeignKey(db_column='file_type_seq', on_delete=django.db.models.deletion.PROTECT, related_name='files', to='core.filetypes')),
            ],
            options={
                'db_table': 'files',
                'ordering': ['file_name'],
            },
        ),
        migrations.CreateModel(
            name='DataFileComments',
            fields=[
                ('id', models.AutoField(db_column='file_comment_seq', primary_key=True, serialize=False)),
                ('comment', models.CharField(db_column='comment', max_length=255, verbose_name='Comments')),
                ('comment_date', models.DateTimeField(auto_now_add=True, db_column='comment_date')),
                ('author', models.ForeignKey(db_column='author_seq', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('datafile', models.ForeignKey(db_column='file_seq', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.datafiles', verbose_name='Data File')),
            ],
            options={
                'db_table': 'file_comments',
                'ordering': ['comment_date'],
            },
        ),
        migrations.CreateModel(
            name='DatasetComments',
            fields=[
                ('id', models.AutoField(db_column='dataset_comment_seq', primary_key=True, serialize=False)),
                ('comment', models.CharField(db_column='comment', max_length=255, verbose_name='Comments')),
                ('comment_date', models.DateTimeField(auto_now_add=True, db_column='comment_date')),
                ('author', models.ForeignKey(db_column='author_seq', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(db_column='dataset_seq', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.dataset', verbose_name='Dataset')),
            ],
            options={
                'db_table': 'dataset_comments',
                'ordering': ['comment_date'],
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='status',
            field=models.ForeignKey(db_column='dataset_status_seq', on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='core.datasetstatus', verbose_name='Dataset Status'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_type',
            field=models.ForeignKey(db_column='data_type_seq', on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='core.datatypes'),
        ),
        migrations.CreateModel(
            name='GroupProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='MissionRegions',
            fields=[
                ('id', models.AutoField(db_column='mission_region_seq', primary_key=True, serialize=False)),
                ('leg', models.ForeignKey(db_column='leg_seq', on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='core.legs', verbose_name='Leg')),
                ('region', models.ForeignKey(db_column='geographic_region_seq', on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='core.geographicregions', verbose_name='Region')),
            ],
            options={
                'db_table': 'mission_regions',
                'ordering': ['leg', 'region'],
            },
        ),
        migrations.CreateModel(
            name='MissionComments',
            fields=[
                ('id', models.AutoField(db_column='mission_comment_seq', primary_key=True, serialize=False)),
                ('comment', models.CharField(db_column='comment', max_length=255, verbose_name='Comments')),
                ('comment_date', models.DateTimeField(auto_now_add=True, db_column='comment_date')),
                ('author', models.ForeignKey(db_column='author_seq', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(db_column='mission_seq', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.missions', verbose_name='Mission')),
            ],
            options={
                'db_table': 'mission_comments',
                'ordering': ['comment_date'],
            },
        ),
        migrations.AddField(
            model_name='legs',
            name='mission',
            field=models.ForeignKey(db_column='mission_seq', on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='core.missions', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='mission',
            field=models.ForeignKey(db_column='mission_seq', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='core.missions'),
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=50, unique=True, verbose_name='Name')),
                ('acronym', models.CharField(blank=True, db_column='acronym', max_length=25, null=True, verbose_name='Acronym')),
                ('code', models.IntegerField(blank=True, db_column='code', null=True, verbose_name='Code')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description')),
                ('country', models.ForeignKey(db_column='country_seq', on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.countries', verbose_name='Country')),
            ],
            options={
                'db_table': 'lu_organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MissionOrganizations',
            fields=[
                ('id', models.AutoField(db_column='mission_organization_seq', primary_key=True, serialize=False)),
                ('mission', models.ForeignKey(db_column='mission_seq', on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='core.missions', verbose_name='Mission')),
                ('organization', models.ForeignKey(db_column='organization_seq', on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='core.organizations', verbose_name='Organization')),
            ],
            options={
                'db_table': 'mission_organizations',
                'ordering': ['mission', 'organization'],
            },
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.AutoField(db_column='platform_seq', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', default='Unknown', help_text='Platform name or description', max_length=100, verbose_name='Name')),
                ('call_sign', models.CharField(db_column='call_sign', default='Unknown', help_text='Platform call sign, if applicable', max_length=10, verbose_name='Call Sign')),
                ('max_speed', models.FloatField(db_column='maximum_speed', default=-999, help_text='Maximum speed of the platform in knots', verbose_name='Max Speed')),
                ('ices_code', models.CharField(blank=True, db_column='ices_code', help_text='ICES code', max_length=4, null=True, verbose_name='ICES Code')),
                ('ship_code', models.CharField(blank=True, db_column='ship_code', help_text='OSCruise code', max_length=6, null=True, verbose_name='Ship Code')),
                ('country', models.ForeignKey(db_column='country_seq', on_delete=django.db.models.deletion.PROTECT, related_name='platforms', to='core.countries', verbose_name='Country')),
            ],
            options={
                'db_table': 'lu_platforms',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='missions',
            name='platform',
            field=models.ForeignKey(db_column='platform_seq', on_delete=django.db.models.deletion.PROTECT, related_name='cruises', to='core.platforms', verbose_name='Ship/Platform'),
        ),
        migrations.CreateModel(
            name='MissionParticipants',
            fields=[
                ('id', models.AutoField(db_column='mission_participant_seq', primary_key=True, serialize=False)),
                ('leg', models.ForeignKey(db_column='leg_seq', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.legs', verbose_name='Leg')),
                ('participant', models.ForeignKey(db_column='participant_seq', on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='core.participants', verbose_name='Participant')),
                ('position', models.ForeignKey(db_column='position_seq', on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='core.positions', verbose_name='Position')),
            ],
            options={
                'db_table': 'mission_participants',
                'ordering': ['leg', 'position'],
            },
        ),
        migrations.AddField(
            model_name='missions',
            name='program',
            field=models.ForeignKey(db_column='program_seq', on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='core.programs', verbose_name='Program'),
        ),
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.AutoField(db_column='processing_seq', primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(auto_now=True, db_column='assigned_date')),
                ('assigned_to', models.ForeignKey(db_column='assigned_to', on_delete=django.db.models.deletion.PROTECT, related_name='processing', to=settings.AUTH_USER_MODEL, verbose_name='Assigned')),
                ('dataset', models.ForeignKey(db_column='dataset_seq', on_delete=django.db.models.deletion.CASCADE, related_name='processing', to='core.dataset', verbose_name='Dataset')),
                ('status', models.ForeignKey(db_column='status_seq', on_delete=django.db.models.deletion.PROTECT, related_name='processing', to='core.status', verbose_name='Status')),
            ],
        ),
    ]
