# Generated by Django 5.2.5 on 2025-08-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='DataStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='GeographicRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Program name')),
                ('description', models.TextField(verbose_name='Program description')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('roles', models.ManyToManyField(blank=True, related_name='contacts', to='core.contactroles', verbose_name='Roles')),
            ],
        ),
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('descriptor', models.CharField(max_length=20, verbose_name='Descriptor')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('chief_scientists', models.ManyToManyField(blank=True, related_name='chief_scientists', to='core.contactroles', verbose_name='Chief scientists')),
                ('locations', models.ManyToManyField(blank=True, related_name='locations', to='core.geographicregions', verbose_name='Locations')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_file_location', models.CharField(max_length=255, verbose_name='File location')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cruise')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.datastatus', verbose_name='Process Status')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.datatypes')),
                ('instruments', models.ManyToManyField(blank=True, related_name='instruments', to='core.instruments', verbose_name='Instruments')),
            ],
        ),
        migrations.CreateModel(
            name='MooredInstruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(help_text='Serial Number or name given to the moored instrument', max_length=20, verbose_name='Name')),
                ('instruments', models.ManyToManyField(blank=True, related_name='moored_instruments', to='core.instruments', verbose_name='Instruments')),
            ],
        ),
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cruise')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programs')),
            ],
        ),
    ]
