# Generated by Django 5.2.5 on 2026-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='code',
            field=models.IntegerField(blank=True, db_column='code', help_text='2-digit country code', null=True, verbose_name='Code'),
        ),
    ]
