# Generated by Django 5.2.5 on 2025-08-15 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the cruise e.g 'CAR2025002'", max_length=20, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('descriptor', models.CharField(blank=True, help_text="MEDS assigned description of the cruise e.g '18QL25002'", max_length=20, null=True, verbose_name='Descriptor')),
                ('chief_scientists', models.ManyToManyField(blank=True, related_name='chief_scientists', to='core.contactroles', verbose_name='Chief scientists')),
                ('locations', models.ManyToManyField(blank=True, related_name='locations', to='core.geographicregions', verbose_name='Locations')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cruises'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cruises'),
        ),
        migrations.DeleteModel(
            name='Cruise',
        ),
    ]
