# Generated by Django 5.2.5 on 2025-08-24 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_default_platform(apps, schema_editor):
    Platform = apps.get_model('core', 'Platforms')
    Platform.objects.create(name='Default Platform', ship_code='XX00')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('ship_code', models.CharField(help_text='ICES (https://vocab.ices.dk/) code consists of 2 character country code and a 2 character ship code for every unique vessel.', max_length=4, null=True, verbose_name='Ship Code')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_default_platform, lambda app, schema_editor: None),
        migrations.CreateModel(
            name='DataFileIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(verbose_name='Issue Description')),
                ('datafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_issues', to='core.datafiles', verbose_name='Data File')),
            ],
        ),
        migrations.AddField(
            model_name='cruises',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cruises', to='core.platforms', verbose_name='Ship/Platform'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing', to=settings.AUTH_USER_MODEL, verbose_name='Assigned')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing', to='core.dataset', verbose_name='Dataset')),
            ],
        ),
    ]
