# Generated by Django 5.2.5 on 2025-09-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafiles',
            name='file',
            field=models.FileField(max_length=255, upload_to='', verbose_name='File'),
        ),
    ]
