# Generated by Django 5.2.5 on 2026-03-16 13:10

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_countries_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='country',
            field=models.ForeignKey(db_column='country_seq', default=core.models.get_default_platform_country, on_delete=django.db.models.deletion.PROTECT, related_name='platforms', to='core.countries', verbose_name='Country'),
        ),
    ]
