# Generated by Django 5.2.5 on 2026-03-12 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_datafiles_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(db_column='COUNTRY_SEQ', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='COUNTRY_NAME', max_length=35)),
                ('code', models.CharField(blank=True, db_column='COUNTRY_CODE', help_text='2-character Country code', max_length=2, null=True)),
            ],
            options={
                'db_table': 'LU_COUNTRY',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='platforms',
            options={'ordering': ['platform']},
        ),
        migrations.RemoveField(
            model_name='platforms',
            name='name',
        ),
        migrations.AddField(
            model_name='platforms',
            name='call_sign',
            field=models.CharField(blank=True, db_column='CALL_SIGN', help_text='Platform call sign, if applicable', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='platforms',
            name='ices_code',
            field=models.CharField(blank=True, db_column='ICES_CODE', help_text='ICES code', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='platforms',
            name='max_speed',
            field=models.IntegerField(blank=True, db_column='MAXIMUM_SPEED', help_text='Maximum speed of the platform in knots', null=True),
        ),
        migrations.AddField(
            model_name='platforms',
            name='platform',
            field=models.CharField(db_column='PLATFORM', default='', help_text='Platform name or description', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platforms',
            name='id',
            field=models.AutoField(db_column='PLATFORM_SEQ', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='ship_code',
            field=models.CharField(blank=True, db_column='SHIP_CODE', help_text='OSCruise code', max_length=6, null=True),
        ),
        migrations.AlterModelTable(
            name='platforms',
            table='LU_PLATFORM',
        ),
        migrations.AddField(
            model_name='platforms',
            name='country',
            field=models.ForeignKey(blank=True, db_column='COUNTRY_SEQ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='core.country'),
        ),
    ]
