# Generated by Django 5.2.5 on 2025-08-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_geographicregions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number of an instrument if it exists', max_length=255, null=True, verbose_name='Serial Number'),
        ),
    ]
