# Generated by Django 5.2.5 on 2025-08-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cruises_alter_data_cruise_alter_missions_cruise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruises',
            name='chief_scientists',
            field=models.ManyToManyField(blank=True, related_name='chief_scientists', to='core.contacts', verbose_name='Chief scientists'),
        ),
    ]
