# Generated by Django 5.2.5 on 2025-08-16 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cruises_chief_scientists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='contactroles',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='datastatus',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='datatypes',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='geographicregions',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='core.cruises'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='core.programs'),
        ),
        migrations.AlterField(
            model_name='mooredinstruments',
            name='descriptor',
            field=models.CharField(help_text='Serial Number or name given to the moored instrument', max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Program name'),
        ),
        migrations.AlterUniqueTogether(
            name='contacts',
            unique_together={('first_name', 'last_name')},
        ),
    ]
