# Generated by Django 5.2.5 on 2026-03-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_platforms_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='call_sign',
            field=models.CharField(db_column='call_sign', default='------', help_text='Platform call sign, if applicable', max_length=10, verbose_name='Call Sign'),
        ),
    ]
