# Generated by Django 5.2.5 on 2025-08-17 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_instruments_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_data', to='core.cruises'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mission_data', to='core.datatypes'),
        ),
        migrations.AlterField(
            model_name='data',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='mission_data', to='core.instruments', verbose_name='Instruments'),
        ),
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mission_data', to='core.datastatus', verbose_name='Process Status'),
        ),
    ]
