# Generated by Django 5.2.5 on 2026-03-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_platforms_call_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='legs',
            name='regions',
            field=models.ManyToManyField(through='core.MissionRegions', to='core.geographicregions', verbose_name='Geographic Regions'),
        ),
        migrations.AlterField(
            model_name='missionregions',
            name='leg',
            field=models.ForeignKey(db_column='leg_seq', on_delete=django.db.models.deletion.CASCADE, to='core.legs', verbose_name='Leg'),
        ),
    ]
