# Generated by Django 5.2.5 on 2026-03-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_dataset_instruments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruises',
            name='programs',
        ),
        migrations.DeleteModel(
            name='Programs',
        ),
    ]
