# Generated by Django 5.2.5 on 2025-08-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_processing_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafiles',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is archived'),
        ),
    ]
