# Generated by Django 5.2.5 on 2025-08-18 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_data_cruise_alter_data_data_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='file',
        ),
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='core.data')),
            ],
        ),
    ]
