# Generated by Django 5.2.5 on 2026-03-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cruises_programs_delete_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='short_name',
            field=models.CharField(blank=True, db_column='SHORT_NAME', help_text='2-character country code', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, db_column='CODE', help_text='2-digit country code', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_column='NAME', max_length=35),
        ),
    ]
