# Generated by Django 5.2.5 on 2025-08-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_data_file_datafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='legacy_file_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File location'),
        ),
    ]
