# Generated by Django 5.2.5 on 2026-03-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_legs_regions_alter_missionregions_leg'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legs',
            unique_together={('mission', 'number')},
        ),
    ]
