# Generated by Django 5.2.5 on 2026-03-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_legs_regions_alter_missionregions_leg'),
    ]

    operations = [
        migrations.AddField(
            model_name='missions',
            name='organizations',
            field=models.ManyToManyField(through='core.MissionOrganizations', to='core.organizations', verbose_name='Organizations'),
        ),
        migrations.AlterField(
            model_name='missionorganizations',
            name='mission',
            field=models.ForeignKey(db_column='mission_seq', on_delete=django.db.models.deletion.CASCADE, related_name='mission_organizations', to='core.missions', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='missionorganizations',
            name='organization',
            field=models.ForeignKey(db_column='organization_seq', on_delete=django.db.models.deletion.PROTECT, related_name='organization_missions', to='core.organizations', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='missionparticipants',
            name='leg',
            field=models.ForeignKey(db_column='leg_seq', on_delete=django.db.models.deletion.CASCADE, related_name='leg_participants', to='core.legs', verbose_name='Leg'),
        ),
        migrations.AlterField(
            model_name='missionparticipants',
            name='participant',
            field=models.ForeignKey(db_column='participant_seq', on_delete=django.db.models.deletion.PROTECT, related_name='participant_legs', to='core.participants', verbose_name='Participant'),
        ),
        migrations.AlterField(
            model_name='missionparticipants',
            name='position',
            field=models.ForeignKey(db_column='position_seq', on_delete=django.db.models.deletion.PROTECT, related_name='position_legs', to='core.positions', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='missionregions',
            name='leg',
            field=models.ForeignKey(db_column='leg_seq', on_delete=django.db.models.deletion.CASCADE, related_name='leg_regions', to='core.legs', verbose_name='Leg'),
        ),
        migrations.AlterField(
            model_name='missionregions',
            name='region',
            field=models.ForeignKey(db_column='geographic_region_seq', on_delete=django.db.models.deletion.PROTECT, related_name='region_legs', to='core.geographicregions', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='id',
            field=models.AutoField(db_column='participant_seq', primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='legs',
            unique_together={('mission', 'number')},
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='data',
            field=models.ForeignKey(db_column='dataset_seq', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.datasets'),
        ),
        migrations.AlterField(
            model_name='datasetcomments',
            name='dataset',
            field=models.ForeignKey(db_column='dataset_seq', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.datasets', verbose_name='Dataset'),
        ),
        migrations.AlterField(
            model_name='processingstatus',
            name='dataset',
            field=models.ForeignKey(db_column='dataset_seq', on_delete=django.db.models.deletion.CASCADE, related_name='processing', to='core.datasets', verbose_name='Dataset'),
        ),
    ]
