# Generated by Django 5.2.5 on 2025-08-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_datafiles_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafiles',
            options={'ordering': ['file_name']},
        ),
        migrations.AlterField(
            model_name='datafileissues',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
