# Generated by Django 5.2.5 on 2026-03-20 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_missions_organizations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legs',
            options={'ordering': ['start_date']},
        ),
    ]
