# Generated by Django 5.2.5 on 2026-03-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_country_short_name_alter_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(db_column='country_seq', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=35, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, db_column='short_name', help_text='2-character country code', max_length=2, null=True, verbose_name='Short Name')),
                ('code', models.CharField(blank=True, db_column='code', help_text='2-digit country code', max_length=2, null=True, verbose_name='Code')),
            ],
            options={
                'db_table': 'lu_countries',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='platforms',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='platforms',
            name='platform',
        ),
        migrations.AddField(
            model_name='platforms',
            name='name',
            field=models.CharField(db_column='name', default='Unknown', help_text='Platform name or description', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='geographicregions',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='geographicregions',
            name='name',
            field=models.CharField(db_column='name', max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='call_sign',
            field=models.CharField(blank=True, db_column='call_sign', help_text='Platform call sign, if applicable', max_length=10, null=True, verbose_name='Call Sign'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='ices_code',
            field=models.CharField(blank=True, db_column='ices_code', help_text='ICES code', max_length=4, null=True, verbose_name='ICES Code'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='id',
            field=models.AutoField(db_column='platform_seq', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='max_speed',
            field=models.FloatField(blank=True, db_column='maximum_speed', help_text='Maximum speed of the platform in knots', null=True, verbose_name='Max Speed'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='ship_code',
            field=models.CharField(blank=True, db_column='ship_code', help_text='OSCruise code', max_length=6, null=True, verbose_name='Ship Code'),
        ),
        migrations.AlterModelTable(
            name='geographicregions',
            table='lu_geographic_regions',
        ),
        migrations.AlterModelTable(
            name='platforms',
            table='lu_platforms',
        ),
        migrations.AlterField(
            model_name='platforms',
            name='country',
            field=models.ForeignKey(blank=True, db_column='country_seq', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='core.countries', verbose_name='Country'),
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100, unique=True, verbose_name='Name')),
                ('acronym', models.CharField(db_column='acronym', max_length=255, verbose_name='Description')),
                ('code', models.CharField(db_column='code', max_length=255, verbose_name='Description')),
                ('description', models.CharField(db_column='description', max_length=255, verbose_name='Description')),
                ('country', models.ForeignKey(db_column='country_seq', on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='core.countries', verbose_name='Country')),
            ],
            options={
                'db_table': 'lu_organizations',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
