# Generated by Django 5.2.5 on 2025-08-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_data_legacy_file_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datafile',
            new_name='Datafiles',
        ),
    ]
