# Generated by Django 5.2.5 on 2026-03-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_legs_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='id',
            field=models.AutoField(db_column='participant_seq', primary_key=True, serialize=False),
        ),
    ]
