# Generated by Django 5.2.5 on 2026-03-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_countries_alter_platforms_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first_name', max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(db_column='last_name', max_length=50, verbose_name='Name')),
            ],
            options={
                'db_table': 'lu_participants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
