# Generated by Django 5.2.5 on 2026-03-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_legs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missioncomments',
            options={'ordering': ['-comment_date']},
        ),
        migrations.RenameField(
            model_name='datafiles',
            old_name='data',
            new_name='dataset',
        ),
        migrations.AlterField(
            model_name='platforms',
            name='ices_code',
            field=models.CharField(blank=True, db_column='ices_code', help_text="<a href='https://vocab.ices.dk/' role='link' title='visit the ICES vocabulary lookup tool' target='_blank' rel='noopener noreferrer'><span class='bi bi-globe2 me-1'></span>ICES vocabulary Lookup</a>", max_length=4, null=True, verbose_name='ICES Code'),
        ),
    ]
