# Generated by Django 5.2.5 on 2026-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_missioncomments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='acronym',
            field=models.CharField(blank=True, db_column='acronym', max_length=10, null=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='name',
            field=models.CharField(db_column='name', max_length=65, unique=True, verbose_name='Name'),
        ),
    ]
