# Generated by Django 5.2.5 on 2026-03-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=30, verbose_name='Name')),
                ('description', models.CharField(db_column='description', max_length=255, verbose_name='Description')),
            ],
            options={
                'db_table': 'lu_positions',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='participants',
            name='first_name',
            field=models.CharField(db_column='first_name', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='last_name',
            field=models.CharField(db_column='last_name', max_length=50, verbose_name='Last Name'),
        ),
    ]
