# Generated by Django 5.2.5 on 2025-08-22 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_datafiles_file_name_datafiles_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafiles',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
