# Generated by Django 5.2.5 on 2026-03-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_positions_alter_participants_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatypes',
            name='description',
            field=models.CharField(db_column='description', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='datatypes',
            name='name',
            field=models.CharField(db_column='name', max_length=25, unique=True, verbose_name='Name'),
        ),
        migrations.AlterModelTable(
            name='datatypes',
            table='lu_data_types',
        ),
    ]
