# Generated by Django 5.2.5 on 2026-03-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_programs_acronym_alter_programs_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetLocations',
            fields=[
                ('id', models.AutoField(db_column='dataset_location_seq', primary_key=True, serialize=False)),
                ('input_dir', models.CharField(blank=True, help_text='Directory, within a mission directory on MEDIA_IN, Mar-DID will look in for bulk uploading files', max_length=100, null=True, verbose_name='Input Directory')),
                ('output_dir', models.CharField(blank=True, help_text='Directory Mar-DID create, within a mission directory on MEDIA_OUT, to write dataset files to.', max_length=100, null=True, verbose_name='Output Directory')),
                ('data_type', models.ForeignKey(db_column='dataset_seq', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.datatypes', verbose_name='Dataset')),
            ],
            options={
                'db_table': 'APPLICATION_CONFIGURATION_DATASET_LOCATIONS',
                'ordering': ['data_type'],
            },
        ),
    ]
