# Generated by Django 5.2.5 on 2025-08-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_datafiles_submitted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafiles',
            name='submitted_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
