# Generated by Django 5.2.5 on 2026-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_datatypes_description_alter_datatypes_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=45, unique=True, verbose_name='Name')),
                ('description', models.CharField(db_column='description', max_length=255, verbose_name='Description')),
            ],
            options={
                'db_table': 'lu_status',
                'ordering': ['name'],
            },
        ),
    ]
