# Generated by Django 5.2.5 on 2026-03-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_datasetlocations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legs',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='legs',
            name='number',
        ),
    ]
