# Generated by Django 5.2.5 on 2026-03-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_legs_unique_together_remove_legs_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafiles',
            name='file_path',
            field=models.CharField(blank=True, db_column='file_path', max_length=100, null=True, verbose_name='File Path'),
        ),
        migrations.AddField(
            model_name='legs',
            name='descriptor_approved',
            field=models.BooleanField(db_column='descriptor_approved', default=False, verbose_name='Descriptor Approved'),
        ),
    ]
