# Generated by Django 5.2.5 on 2026-03-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(db_column='extension', max_length=25, verbose_name='Extension')),
                ('description', models.CharField(db_column='description', max_length=255, verbose_name='Description')),
            ],
            options={
                'db_table': 'lu_file_types',
                'ordering': ['extension'],
            },
        ),
    ]
