# Generated by Django 5.2.5 on 2025-08-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cruises_data_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatypes',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='geographicregions',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='instruments',
            options={'ordering': ['name', 'serial_number']},
        ),
        migrations.AlterModelOptions(
            name='programs',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='cruises',
            name='programs',
            field=models.ManyToManyField(related_name='programs', to='core.programs', verbose_name='programs'),
        ),
        migrations.DeleteModel(
            name='Missions',
        ),
    ]
