# Generated by Django 5.2.5 on 2026-03-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_datafiles_file_path_legs_descriptor_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatypes',
            name='legacy',
            field=models.BooleanField(db_column='legacy', default=True, verbose_name='Legacy Code'),
        ),
        migrations.AddField(
            model_name='geographicregions',
            name='legacy',
            field=models.BooleanField(db_column='legacy', default=True, verbose_name='Legacy Code'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='legacy',
            field=models.BooleanField(db_column='legacy', default=True, verbose_name='Legacy Code'),
        ),
        migrations.AddField(
            model_name='participants',
            name='legacy',
            field=models.BooleanField(db_column='legacy', default=True, verbose_name='Legacy Code'),
        ),
        migrations.AddField(
            model_name='platforms',
            name='legacy',
            field=models.BooleanField(db_column='legacy', default=True, verbose_name='Legacy Code'),
        ),
        migrations.AddField(
            model_name='programs',
            name='legacy',
            field=models.BooleanField(db_column='legacy', default=True, verbose_name='Legacy Code'),
        ),
    ]
