# Generated by Django 5.2.5 on 2026-03-13 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_cruises_missions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastatus',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='missions',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='missions',
            name='chief_scientists',
        ),
        migrations.RemoveField(
            model_name='missions',
            name='data_managers',
        ),
        migrations.RemoveField(
            model_name='missions',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='missions',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='missions',
            name='start_date',
        ),
        migrations.AddField(
            model_name='missions',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='missions',
            name='ppt_id',
            field=models.IntegerField(blank=True, db_column='ppt_id', help_text='Project Planning Tool ID to link to project details', null=True, verbose_name='PPT id'),
        ),
        migrations.AlterField(
            model_name='datastatus',
            name='description',
            field=models.CharField(db_column='description', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='datastatus',
            name='name',
            field=models.CharField(db_column='name', max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='descriptor',
            field=models.CharField(blank=True, db_column='meds_descriptor', help_text="MEDS assigned description of the cruise e.g '18QL25002'", max_length=20, null=True, verbose_name='Descriptor'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='name',
            field=models.CharField(db_column='name', help_text="The name of the cruise e.g 'CAR2025002'", max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='platform',
            field=models.ForeignKey(db_column='platform_seq', on_delete=django.db.models.deletion.PROTECT, related_name='cruises', to='core.platforms', verbose_name='Ship/Platform'),
        ),
        migrations.AlterModelTable(
            name='datastatus',
            table='lu_data_status',
        ),
        migrations.AlterModelTable(
            name='missions',
            table='missions',
        ),
        migrations.CreateModel(
            name='Legs',
            fields=[
                ('id', models.AutoField(db_column='leg_seq', primary_key=True, serialize=False)),
                ('number', models.IntegerField(db_column='number', verbose_name='Leg Number')),
                ('start_date', models.DateField(db_column='start_date', verbose_name='Start Date')),
                ('end_date', models.DateField(db_column='end_date', verbose_name='End Date')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description')),
                ('mission', models.ForeignKey(db_column='mission_seq', on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='core.missions', verbose_name='Mission')),
            ],
            options={
                'db_table': 'legs',
                'ordering': ['number'],
            },
        ),
    ]
