# Generated by Django 5.2.5 on 2026-03-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_datatypes_legacy_geographicregions_legacy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafilecomments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='datasetcomments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='missioncomments',
            options={},
        ),
    ]
