# Generated by Django 5.2.5 on 2026-03-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_datafilecomments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetlocations',
            options={'ordering': ['datatype']},
        ),
        migrations.AlterModelOptions(
            name='datasets',
            options={'ordering': ['mission', 'datatype']},
        ),
        migrations.RenameField(
            model_name='datasetlocations',
            old_name='data_type',
            new_name='datatype',
        ),
        migrations.RenameField(
            model_name='datasets',
            old_name='data_type',
            new_name='datatype',
        ),
    ]
