# Generated by Django 5.2.5 on 2026-03-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_datasetlocations_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legs',
            name='descriptor_approved',
        ),
        migrations.AddField(
            model_name='missions',
            name='descriptor_approved',
            field=models.BooleanField(db_column='descriptor_approved', default=False, help_text='Indicates if MEDS has approved the descriptor for this mission', verbose_name='Descriptor Approved'),
        ),
    ]
