# Generated by Django 5.2.5 on 2026-03-13 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_cruise_dataset_mission_missionparticipants'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionRegions',
            fields=[
                ('id', models.AutoField(db_column='mission_region_seq', primary_key=True, serialize=False)),
                ('leg', models.ForeignKey(db_column='leg_seq', on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='core.legs', verbose_name='Leg')),
                ('region', models.ForeignKey(db_column='geographic_region_seq', on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='core.geographicregions', verbose_name='Region')),
            ],
            options={
                'db_table': 'mission_regions',
                'ordering': ['leg', 'region'],
            },
        ),
    ]
