# Generated by Django 5.2.5 on 2026-03-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_legs_descriptor_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafiles',
            name='archived_date',
            field=models.DateTimeField(blank=True, db_column='archived_date', null=True, verbose_name='Archived Date'),
        ),
    ]
