# Generated by Django 5.2.5 on 2026-03-13 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_dataset_data_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafiles',
            name='file',
        ),
        migrations.AddField(
            model_name='datafiles',
            name='file_type',
            field=models.ForeignKey(db_column='file_type_seq', default=0, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='core.filetypes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='data',
            field=models.ForeignKey(db_column='dataset_seq', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.dataset'),
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='file_name',
            field=models.CharField(db_column='file_name', max_length=50, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='id',
            field=models.AutoField(db_column='file_seq', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='is_archived',
            field=models.BooleanField(db_column='is_archived', default=False, verbose_name='Is archived'),
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='submitted_by',
            field=models.ForeignKey(db_column='submitted_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datafiles',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True, db_column='submitted_date'),
        ),
        migrations.AlterModelTable(
            name='datafiles',
            table='files',
        ),
        migrations.CreateModel(
            name='DataFileComments',
            fields=[
                ('id', models.AutoField(db_column='file_comment_seq', primary_key=True, serialize=False)),
                ('comment', models.CharField(db_column='comment', max_length=255, verbose_name='Comments')),
                ('comment_date', models.DateTimeField(auto_now_add=True, db_column='comment_date')),
                ('author', models.ForeignKey(db_column='author_seq', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('datafile', models.ForeignKey(db_column='file_seq', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.datafiles', verbose_name='Data File')),
            ],
            options={
                'db_table': 'file_comments',
                'ordering': ['comment_date'],
            },
        ),
        migrations.DeleteModel(
            name='DataFileIssues',
        ),
    ]
