# Generated by Django 5.2.5 on 2026-04-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_datafiles_archived_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legs',
            options={'ordering': ['start_date', 'end_date']},
        ),
    ]
