# Generated by Django 5.2.5 on 2026-04-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_legs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missions',
            name='name',
            field=models.CharField(db_column='name', help_text="The name of the cruise e.g 'CAR2025002'", max_length=20, unique=True, verbose_name='Name'),
        ),
    ]
