# Generated by Django 5.2.5 on 2026-03-13 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_datafiles_file_datafiles_file_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafilecomments',
            name='datafile',
            field=models.ForeignKey(db_column='file_seq', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.datafiles', verbose_name='Data File'),
        ),
        migrations.CreateModel(
            name='DatasetComments',
            fields=[
                ('id', models.AutoField(db_column='dataset_comment_seq', primary_key=True, serialize=False)),
                ('comment', models.CharField(db_column='comment', max_length=255, verbose_name='Comments')),
                ('comment_date', models.DateTimeField(auto_now_add=True, db_column='comment_date')),
                ('author', models.ForeignKey(db_column='author_seq', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(db_column='dataset_seq', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.dataset', verbose_name='Dataset')),
            ],
            options={
                'db_table': 'dataset_comments',
                'ordering': ['comment_date'],
            },
        ),
    ]
