# Generated by Django 5.2.5 on 2026-04-23 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_missions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetlocations',
            name='datatype',
            field=models.OneToOneField(db_column='dataset_seq', on_delete=django.db.models.deletion.CASCADE, related_name='location', to='core.datatypes', verbose_name='Dataset'),
        ),
    ]
