# Generated by Django 5.2.5 on 2026-03-13 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_datafilecomments_datafile_datasetcomments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionComments',
            fields=[
                ('id', models.AutoField(db_column='mission_comment_seq', primary_key=True, serialize=False)),
                ('comment', models.CharField(db_column='comment', max_length=255, verbose_name='Comments')),
                ('comment_date', models.DateTimeField(auto_now_add=True, db_column='comment_date')),
                ('author', models.ForeignKey(db_column='author_seq', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(db_column='mission_seq', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.missions', verbose_name='Mission')),
            ],
            options={
                'db_table': 'mission_comments',
                'ordering': ['comment_date'],
            },
        ),
    ]
