# Generated by Django 5.2.5 on 2026-03-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_missioncomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='code',
            field=models.IntegerField(blank=True, help_text='2-digit country code', null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(db_column='name', max_length=45, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='short_name',
            field=models.CharField(db_column='short_name', default='--', help_text='2-character country code', max_length=2, verbose_name='Short Name'),
            preserve_default=False,
        ),
    ]
