# Generated by Django 5.2.5 on 2026-04-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_datasetlocations_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafiles',
            name='file_name',
            field=models.CharField(db_column='file_name', max_length=100, verbose_name='File Name'),
        ),
    ]
