# Generated by Django 5.2.5 on 2026-03-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_datasetstatus_alter_dataset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatypes',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterModelTable(
            name='datatypes',
            table='lu_dataset_types',
        ),
    ]
