# Generated by Django 5.2.5 on 2026-03-13 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_datatypes_description_alter_datatypes_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='acronym',
            field=models.CharField(blank=True, db_column='acronym', max_length=25, null=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='code',
            field=models.IntegerField(blank=True, db_column='code', null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='country',
            field=models.ForeignKey(db_column='country_seq', on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.countries', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='name',
            field=models.CharField(db_column='name', max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
