# Generated by Django 5.2.5 on 2026-03-13 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_organizations_acronym_alter_organizations_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='call_sign',
            field=models.CharField(db_column='call_sign', default='Unknown', help_text='Platform call sign, if applicable', max_length=10, verbose_name='Call Sign'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='country',
            field=models.ForeignKey(db_column='country_seq', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='platforms', to='core.countries', verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platforms',
            name='max_speed',
            field=models.FloatField(db_column='maximum_speed', default=-999, help_text='Maximum speed of the platform in knots', verbose_name='Max Speed'),
        ),
    ]
