# Generated by Django 5.2.5 on 2026-03-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_platforms_call_sign_alter_platforms_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description'),
        ),
    ]
