# Generated by Django 5.2.5 on 2026-03-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_status_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=45, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'lu_programs',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='missions',
            name='description',
        ),
        migrations.AddField(
            model_name='missions',
            name='program',
            field=models.ForeignKey(db_column='program_seq', default=0, on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='core.programs', verbose_name='Program'),
            preserve_default=False,
        ),
    ]
