# Generated by Django 5.2.5 on 2026-03-13 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_dataset_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.AutoField(db_column='processing_seq', primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(auto_now=True, db_column='assigned_date')),
                ('assigned_to', models.ForeignKey(db_column='assigned_to', on_delete=django.db.models.deletion.PROTECT, related_name='processing', to=settings.AUTH_USER_MODEL, verbose_name='Assigned')),
                ('dataset', models.ForeignKey(db_column='dataset_seq', on_delete=django.db.models.deletion.CASCADE, related_name='processing', to='core.dataset', verbose_name='Dataset')),
                ('status', models.ForeignKey(db_column='status_seq', on_delete=django.db.models.deletion.PROTECT, related_name='processing', to='core.status', verbose_name='Status')),
            ],
        ),
        migrations.DeleteModel(
            name='Processing',
        ),
    ]
