# Generated by Django 5.2.5 on 2025-12-30 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(db_column='CONTACT_SEQ', primary_key=True, serialize=False)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=50)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=50)),
            ],
            options={
                'db_table': 'LU_CONTACT',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(db_column='COUNTRY_SEQ', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='COUNTRY_NAME', max_length=35)),
            ],
            options={
                'db_table': 'LU_COUNTRY',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(db_column='DIVISION_SEQ', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='DIVISION_NAME', max_length=100)),
            ],
            options={
                'db_table': 'LU_DIVISION',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(db_column='EQUIPMENT_TYPE_SEQ', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='EQUIPMENT_TYPE', max_length=35)),
            ],
            options={
                'db_table': 'LU_EQUIPMENT_TYPE',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(db_column='FILE_TYPE_SEQ', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='FILE_TYPE_NAME', max_length=25)),
                ('description', models.CharField(db_column='FILE_TYPE_DESCRIPTION', max_length=100)),
            ],
            options={
                'db_table': 'LU_FILE_TYPE',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='FolderPath',
            fields=[
                ('id', models.AutoField(db_column='FOLDER_PATH_SEQ', primary_key=True, serialize=False)),
                ('path', models.CharField(db_column='FOLDER_PATH_STRING', max_length=10)),
            ],
            options={
                'db_table': 'LU_FOLDER_PATH',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='GeographicRegion',
            fields=[
                ('id', models.AutoField(db_column='GEOGRAPHIC_SEQ', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='GEOGRAPHIC_NAME', max_length=40)),
            ],
            options={
                'db_table': 'LU_GEOGRAPHIC_REGION',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.AutoField(db_column='ROLE_SEQ', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ROLE_NAME', max_length=25)),
                ('description', models.CharField(db_column='ROLE_DESCRIPTION', max_length=50)),
            ],
            options={
                'db_table': 'LU_ROLE',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(db_column='INSTITUTE_SEQ', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='INSTITUTE_NAME', max_length=50)),
            ],
            options={
                'db_table': 'LU_INSTITUTE',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.AutoField(db_column='INSTRUMENT_TYPE_SEQ', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='INSTRUMENT_TYPE', max_length=35)),
            ],
            options={
                'db_table': 'LU_INSTRUMENT_TYPE',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='MissionMetadata',
            fields=[
                ('id', models.AutoField(db_column='MISSION_METADATA_SEQ', primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_column='START_DATE')),
                ('end_date', models.DateField(db_column='END_DATE')),
            ],
            options={
                'db_table': 'MISSION_METADATA',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(db_column='ORGANIZATION_SEQ', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ORGANIZATION_NAME', max_length=100)),
                ('description', models.CharField(db_column='ORGANIZATION_DESCRIPTION', max_length=250)),
            ],
            options={
                'db_table': 'LU_ORGANIZATION',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('id', models.AutoField(db_column='PARAMETER_TYPE_SEQ', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='PARAMETER_TYPE', max_length=25)),
                ('units', models.CharField(db_column='PARAMETER_UNITS', max_length=50)),
            ],
            options={
                'db_table': 'LU_PARAMETER_TYPE',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingState',
            fields=[
                ('id', models.AutoField(db_column='PROCESSING_STATE_SEQ', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='PROCESSING_STATE_NAME', max_length=25)),
                ('description', models.CharField(db_column='PROCESSING_STATE_DESCRIPTION', max_length=100)),
            ],
            options={
                'db_table': 'LU_PROCESSING_STATE',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(db_column='PROGRAM_SEQ', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='PROGRAM_NAME', max_length=50)),
                ('description', models.CharField(db_column='PROGRAM_DESCRIPTION', max_length=250)),
            ],
            options={
                'db_table': 'LU_PROGRAM',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(db_column='PROJECT_SEQ', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='PROJECT_NAME', max_length=100)),
                ('description', models.CharField(db_column='PROJECT_DESCRIPTION', max_length=250)),
            ],
            options={
                'db_table': 'LU_PROJECT',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MissionRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geographic_region', models.ForeignKey(db_column='GEOGRAPHIC_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='mission_regions', to='mardid.geographicregion')),
                ('mission', models.ForeignKey(db_column='MISSION_METADATA_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='mission_regions', to='mardid.missionmetadata')),
            ],
            options={
                'db_table': 'LU_MISSION_REGION',
                'ordering': ['mission__start_date'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(db_column='PLATFORM_SEQ', primary_key=True, serialize=False)),
                ('platform', models.CharField(db_column='PLATFORM', help_text='Platform name or description', max_length=100)),
                ('country', models.ForeignKey(blank=True, db_column='COUNTRY_SEQ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='mardid.country')),
            ],
            options={
                'db_table': 'LU_PLATFORM',
                'ordering': ['platform'],
            },
        ),
    ]
