# Generated by Django 5.2.5 on 2026-01-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mardid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionmetadata',
            name='contact_group',
            field=models.ForeignKey(db_column='CONTACT_GROUP_SEQ', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mission_metadata', to='mardid.grouprole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionmetadata',
            name='institute',
            field=models.ForeignKey(db_column='INSTITCH_SEQ', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mission_metadata', to='mardid.institute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionmetadata',
            name='mission_name',
            field=models.CharField(db_column='MISSION_NAME', default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionmetadata',
            name='nodc_descriptor',
            field=models.CharField(blank=True, db_column='NODC_DESCRIPTOR', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='missionmetadata',
            name='platform',
            field=models.ForeignKey(db_column='PLATFORM_SEQ', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mission_metadata', to='mardid.platform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionmetadata',
            name='program',
            field=models.ForeignKey(db_column='PROGRAM_SEQ', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mission_metadata', to='mardid.program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionmetadata',
            name='project_planning_tool_id',
            field=models.IntegerField(blank=True, db_column='PPT_ID', null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='call_sign',
            field=models.CharField(blank=True, db_column='CALL_SIGN', help_text='Platform call sign, if applicable', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='max_speed',
            field=models.IntegerField(blank=True, db_column='MAXIMUM_SPEED', help_text='Maximum speed of the platform in knots', null=True),
        ),
        migrations.AlterField(
            model_name='missionmetadata',
            name='end_date',
            field=models.DateField(blank=True, db_column='END_DATE', null=True),
        ),
        migrations.AlterField(
            model_name='missionmetadata',
            name='start_date',
            field=models.DateField(blank=True, db_column='START_DATE', null=True),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(db_column='EQUIPMENT_SEQ', primary_key=True, serialize=False)),
                ('equipment_number', models.CharField(blank=True, db_column='EQUIPMENT_NUMBER', max_length=25, null=True)),
                ('serial_number', models.CharField(blank=True, db_column='SERIAL_NUMBER', max_length=50, null=True)),
                ('deployment_date', models.DateField(db_column='DEPLOYMENT_DATE')),
                ('recovery_date', models.DateField(db_column='RECOVERY_DATE')),
                ('start_lat', models.FloatField(blank=True, db_column='START_LATITUDE', null=True)),
                ('start_lon', models.FloatField(blank=True, db_column='START_LONGITUDE', null=True)),
                ('end_lat', models.FloatField(blank=True, db_column='END_LATITUDE', null=True)),
                ('end_lon', models.FloatField(blank=True, db_column='END_LONGITUDE', null=True)),
                ('date_entered', models.DateField(db_column='DATE_ENTERED')),
                ('entered_by', models.ForeignKey(db_column='ENTERED_BY_ID', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='mardid.contact')),
                ('equipment_type', models.ForeignKey(db_column='EQUIPMENT_TYPE', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='mardid.instrumenttype')),
                ('metadata', models.ForeignKey(db_column='MISSION_METADATA_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='mardid.missionmetadata')),
                ('recovery_metadata', models.ForeignKey(blank=True, db_column='RECOVERY_MISSION_METADATA_SEQ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_recoveries', to='mardid.missionmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='DataCollected',
            fields=[
                ('id', models.AutoField(db_column='DATA_COLLECTED_SEQ', primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, db_column='SERIAL_NUMBER', max_length=35, null=True)),
                ('date_entered', models.DateField(db_column='DATE_ENTERED')),
                ('entered_by', models.CharField(db_column='ENTERED_BY', max_length=100)),
                ('date_received', models.DateField(db_column='DATE_RECEIVED')),
                ('loaded_to_odf_archive', models.BooleanField(db_column='LOADED_TO_ODF_ARCHIVE', default=False)),
                ('sent_to_meds', models.BooleanField(db_column='SENT_TO_MEDS', default=False)),
                ('data_processor', models.ForeignKey(db_column='DATA_PROCESSOR_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='data_collected_processors', to='mardid.contact')),
                ('division', models.ForeignKey(blank=True, db_column='DIVISION_SEQ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_collected', to='mardid.division')),
                ('instrument_type', models.ForeignKey(db_column='INSTRUMENT_TYPE_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='data_collected', to='mardid.instrumenttype')),
                ('organization', models.ForeignKey(db_column='ORGANIZATION_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='data_collected', to='mardid.organization')),
                ('parameter_type', models.ForeignKey(db_column='PARAMETER_TYPE_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='data_collected', to='mardid.parametertype')),
                ('principal_investigator', models.ForeignKey(db_column='PI_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='data_collected_pis', to='mardid.contact')),
                ('processing_state', models.ForeignKey(db_column='PROCESSING_STATE_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='data_collected', to='mardid.processingstate')),
                ('equipment', models.ForeignKey(db_column='EQUIPMENT_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='data_collected', to='mardid.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentProject',
            fields=[
                ('id', models.AutoField(db_column='EQUIPMENT_PROJECT_SEQ', primary_key=True, serialize=False)),
                ('equipment', models.ForeignKey(db_column='EQUIPMENT_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_projects', to='mardid.equipment')),
                ('metadata', models.ForeignKey(db_column='MISSION_METADATA_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_projects', to='mardid.missionmetadata')),
                ('project', models.ForeignKey(db_column='PROJECT_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_projects', to='mardid.project')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(db_column='FILE_SEQ', primary_key=True, serialize=False)),
                ('relative_path', models.CharField(db_column='RELATIVE_PATH', max_length=200)),
                ('file_name', models.CharField(db_column='FILE_NAME', max_length=200)),
                ('date_submitted', models.DateField(db_column='DATE_SUBMITTED')),
                ('data_collected', models.ForeignKey(db_column='DATA_COLLECTED_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mardid.datacollected')),
                ('file_type', models.ForeignKey(db_column='FILE_TYPE_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mardid.filetype')),
                ('folder_path', models.ForeignKey(db_column='FOLDER_PATH_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mardid.folderpath')),
                ('metadata', models.ForeignKey(db_column='MISSION_METADATA_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mardid.missionmetadata')),
                ('submitted_by', models.ForeignKey(db_column='SUBMITTED_BY_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mardid.contact')),
            ],
        ),
        migrations.CreateModel(
            name='FileComment',
            fields=[
                ('id', models.AutoField(db_column='FILE_COMMENT_SEQ', primary_key=True, serialize=False)),
                ('comment', models.TextField(db_column='COMMENT')),
                ('date', models.DateField(db_column='FILE_COMMENT_DATE')),
                ('author', models.ForeignKey(db_column='AUTHOR_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='file_comments', to='mardid.contact')),
                ('file', models.ForeignKey(db_column='FILE_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='file_comments', to='mardid.file')),
            ],
            options={
                'db_table': 'FILE_COMMENT',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MissionComment',
            fields=[
                ('id', models.AutoField(db_column='MISSION_COMMENT_SEQ', primary_key=True, serialize=False)),
                ('mission_comment', models.TextField(db_column='MISSION_COMMENT')),
                ('comment_date', models.DateField(db_column='MISSION_COMMENT_DATE')),
                ('author', models.ForeignKey(db_column='AUTHOR_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='mission_comments', to='mardid.contact')),
                ('metadata', models.ForeignKey(db_column='MISSION_METADATA_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='mission_comments', to='mardid.missionmetadata')),
            ],
        ),
    ]
