# Generated by Django 5.2.5 on 2026-01-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mardid', '0002_missionmetadata_contact_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='folder_path',
        ),
        migrations.RemoveField(
            model_name='file',
            name='relative_path',
        ),
        migrations.RemoveField(
            model_name='missionmetadata',
            name='contact_group',
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, db_column='COUNTRY_CODE', help_text='2-character Country code', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='datacollected',
            name='folder_path',
            field=models.ForeignKey(db_column='FOLDER_PATH_SEQ', default='', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mardid.folderpath'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datacollected',
            name='relative_path',
            field=models.CharField(db_column='RELATIVE_PATH', default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='ices_code',
            field=models.CharField(blank=True, db_column='ICES_CODE', help_text='ICES code', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='ship_code',
            field=models.CharField(blank=True, db_column='SHIP_CODE', help_text='OSCruise code', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='datacollected',
            name='entered_by',
            field=models.ForeignKey(db_column='ENTERED_BY', on_delete=django.db.models.deletion.CASCADE, related_name='data_collected', to='mardid.contact'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='entered_by',
            field=models.ForeignKey(db_column='ENTERED_BY', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='mardid.contact'),
        ),
        migrations.AlterField(
            model_name='missionmetadata',
            name='institute',
            field=models.ForeignKey(db_column='INSTITUTE_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='mission_metadata', to='mardid.institute'),
        ),
        migrations.AlterModelTable(
            name='datacollected',
            table='DATA_COLLECTED',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='EQUIPMENT',
        ),
        migrations.AlterModelTable(
            name='equipmentproject',
            table='EQUIPMENT_PROJECT',
        ),
        migrations.AlterModelTable(
            name='file',
            table='FILE',
        ),
        migrations.AlterModelTable(
            name='missioncomment',
            table='MISSION_COMMENT',
        ),
        migrations.AlterModelTable(
            name='missionregion',
            table='MISSION_REGION',
        ),
        migrations.CreateModel(
            name='MissionParticipant',
            fields=[
                ('id', models.AutoField(db_column='PARTICIPANT_SEQ', primary_key=True, serialize=False)),
                ('contact', models.ForeignKey(db_column='CONTACT_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='mission_participant', to='mardid.contact')),
                ('role', models.ForeignKey(db_column='ROLE_SEQ', on_delete=django.db.models.deletion.CASCADE, related_name='mission_participants', to='mardid.grouprole')),
            ],
            options={
                'db_table': 'MISSION_PARTICIPANT',
            },
        ),
        migrations.AddField(
            model_name='missionmetadata',
            name='participant',
            field=models.ForeignKey(db_column='PARTICIPANT_SEQ', default='', on_delete=django.db.models.deletion.CASCADE, related_name='mission_metadata', to='mardid.missionparticipant'),
            preserve_default=False,
        ),
    ]
