# Generated by Django 5.2.5 on 2026-02-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mardid', '0003_remove_file_folder_path_remove_file_relative_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='serial_number',
        ),
    ]
