# Generated by Django 5.2.5 on 2026-02-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mardid', '0004_remove_equipment_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(db_column='DIVISION_NAME', max_length=200),
        ),
    ]
