# Generated by Django 5.2.5 on 2026-02-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mardid', '0005_alter_division_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='description',
            field=models.CharField(blank=True, db_column='EQUIPMENT_TYPE_DESCRIPTION', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='acronym',
            field=models.CharField(blank=True, db_column='INSTITUTE_ACRONYM', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='legacy_code',
            field=models.CharField(blank=True, db_column='INSTITUTE_LEGACY_CODE', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='description',
            field=models.CharField(blank=True, db_column='INSTRUMENT_TYPE_DESCRIPTION', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='description',
            field=models.CharField(db_column='FILE_TYPE_DESCRIPTION', max_length=200),
        ),
    ]
