# Generated by Django 5.2.5 on 2026-02-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mardid', '0006_equipmenttype_description_institute_acronym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(db_column='INSTITUTE_NAME', max_length=100),
        ),
    ]
