# Generated by Django 5.2.5 on 2026-03-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mardid', '0007_alter_institute_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.AddField(
            model_name='country',
            name='short_name',
            field=models.CharField(blank=True, db_column='COUNTRY_SHORT_NAME', help_text='2-character country code', max_length=2, null=True),
        ),
    ]
