# Generated by Django 5.2.5 on 2026-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mardid', '0008_remove_country_code_country_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.IntegerField(blank=True, db_column='COUNTRY_CODE', help_text='2-digit country code', null=True),
        ),
    ]
