# Generated by Django 5.2.5 on 2026-03-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mardid', '0009_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='max_speed',
            field=models.FloatField(blank=True, db_column='MAXIMUM_SPEED', help_text='Maximum speed of the platform in knots', null=True),
        ),
    ]
