# Generated by Django 5.2.5 on 2026-03-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mardid', '0008_remove_datacollected_data_processor_and_more'),
        ('mardid', '0010_alter_platform_max_speed'),
    ]

    operations = [
    ]
